AltaUsuarios/Models/LoginVM.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AltaUsuarios.Models
{
    public class LoginVM
    {
        [Required]
        [Display(Name = "Correo electrónico")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Contraseña { get; set; }

        public string MensajeError { get; set; }
    }
}

AltaUsuarios/Models/ResultadoVM.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AltaUsuarios.Models
{
    public class ResultadoVM
    {
        public string Mensaje { get; set; }

    }
   
}

AltaUsuarios/Models/UsuarioVM.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AltaUsuarios.Models
{
    public class UsuarioVM
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Edad")]
        public int Edad { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        [Display(Name = "Correo electrónico")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string Contraseña { get; set; }
    }
   
}

AltaUsuarios/Controllers/HomeController.cs
using AltaUsuarios.Entidad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AltaUsuarios.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sesion()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult BBDD()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AltaUsuarios/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AltaUsuarios.Models;
using AltaUsuarios.Entidad;

namespace AltaUsuarios.Controllers
{
    public class UsuarioController : Controller
    {
        public ActionResult Index(UsuarioVM usuarioVM)
        {

            return View("Alta", new UsuarioVM());
        }

        [HttpPost]
        public ActionResult Alta(UsuarioVM usuarioVM)
        {
            if (ModelState.IsValid)
            {
                bool modoBBDD;
                bool.TryParse(System.Configuration.ConfigurationManager.AppSettings["GuardadoBBDD"], out modoBBDD);
                if (modoBBDD)
                {
                    //uso de bbdd
                }
                else
                {
                    var listadoUsuarios = Session["Usuarios"] != null ? (List<Usuario>)Session["Usuarios"] : new List<Usuario>();
                    if (listadoUsuarios.Any(x => x.Email.Equals(usuarioVM.Email)))
                    {
                        return View("Resultado", new ResultadoVM() { Mensaje = "Ya existe email." });
                    }
                    else
                    {
                        listadoUsuarios.Add(new Usuario() { Nombre = usuarioVM.Nombre, Contraseña = usuarioVM.Contraseña, Edad = usuarioVM.Edad, Email = usuarioVM.Email });
                        Session["Usuarios"] = listadoUsuarios;
                        return View("Resultado", new ResultadoVM() { Mensaje = "Inserción correcta." });
                    }
                }
                //guardar
            }

            return View();
        }

        public ActionResult Listado()
        {
            var listadoUsuarios = Session["Usuarios"] != null ? (List<Usuario>)Session["Usuarios"] : new List<Usuario>();
            var listadoUsuariosVm = new List<UsuarioVM>();
            foreach (var usuario in listadoUsuarios)
            {
                listadoUsuariosVm.Add(new UsuarioVM() { Nombre = usuario.Nombre, Edad = usuario.Edad, Email = usuario.Email });
            }
            return View(listadoUsuariosVm);
        }

        public ActionResult Login()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public ActionResult Login(LoginVM loginVM)
        {
            bool modoBBDD;
            bool.TryParse(System.Configuration.ConfigurationManager.AppSettings["GuardadoBBDD"], out modoBBDD);
            if (modoBBDD)
            {
                //leer de bbdd
            }
            else
            {
                var listadoUsuarios = Session["Usuarios"] != null ? (List<Usuario>)Session["Usuarios"] : new List<Usuario>();
                if (listadoUsuarios.Any(x => x.Email.Equals(loginVM.Email) && x.Contraseña.Equals(loginVM.Contraseña)))
                {
                    var listadoUsuariosVm = new List<UsuarioVM>();
                    foreach (var usuario in listadoUsuarios)
                    {
                        listadoUsuariosVm.Add(new UsuarioVM() { Nombre = usuario.Nombre, Edad = usuario.Edad, Email = usuario.Email });
                    }
                    return View("Listado", listadoUsuariosVm);
                }
                else
                {
                    loginVM.MensajeError = "Usuario o contraseña invalido.";
                    return View(loginVM);
                }
            }

            return View();
        }
    }
}

AltaUsuarios/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AltaUsuarios/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AltaUsuarios/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <h2>@Resources.Resource.EligeOpcion</h2>
    <div class="col-xs-4">
        <a class="btn btn-primary" href="@Url.Action("Index","Usuario")">@Resources.Resource.Alta</a>
    </div>
    <div class="col-xs-4">
        <a class="btn btn-primary" href="@Url.Action("Listado","Usuario")">@Resources.Resource.Listado</a>
    </div>
    <div class="col-xs-4">
        <a class="btn btn-primary" href="@Url.Action("Login","Usuario")">@Resources.Resource.Login</a>
    </div>
</div>

AltaUsuarios/Views/Shared/Resultado.cshtml
@model AltaUsuarios.Models.ResultadoVM


<h2>@Model.Mensaje</h2>


<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a class="btn btn-primary" href="@Url.Action("Index","Home")">Menú</a>
    </div>
</div>

AltaUsuarios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistemas OEE</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Alta Usuarios", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Listado", "Listado", "Usuario")</li>
                    <li>@Html.ActionLink("Alta", "Index", "Usuario")</li>

                    <li>@Html.ActionLink("Login", "Login", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>prueba</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AltaUsuarios/Views/Usuario/Alta.cshtml
@model AltaUsuarios.Models.UsuarioVM
@{
    ViewBag.Title = Resources.Resource.NuevoUsuario;
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Alta", "Usuario", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Nombre, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nombre, null, htmlAttributes: new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Edad, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Edad, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Edad, null, htmlAttributes: new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, null, htmlAttributes: new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Contraseña, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Contraseña, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Contraseña, null, htmlAttributes: new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="@Resources.Resource.Alta" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AltaUsuarios/Views/Usuario/Listado.cshtml
@model List<AltaUsuarios.Models.UsuarioVM>
@{
    ViewBag.Title = Resources.Resource.Listado;
}

<h2>@ViewBag.Title.</h2>

  <table class="table table-stripped">
      <thead>
          <tr>
              <th>Nombre</th>
              <th>Edad</th>
              <th>Email</th>
          </tr>
      </thead>
      <tbody>
          @foreach (var usuario in Model)
          {
            <tr>
                <td>@usuario.Nombre</td>
                <td>@usuario.Edad</td>
                <td>@usuario.Email</td>
            </tr>

          }
      </tbody>
  </table>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a class="btn btn-primary" href="@Url.Action("Index","Home")">Menú</a>
    </div>
</div>

AltaUsuarios/Views/Usuario/Login.cshtml
@using AltaUsuarios.Models
@model LoginVM
@{
    ViewBag.Title = "Iniciar sesión";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        @if (!String.IsNullOrWhiteSpace(Model.MensajeError))
        {
            <div class="text-danger">
                <h3>@Model.MensajeError</h3>
            </div>
        }
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Usuario", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, null, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Contraseña, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Contraseña, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Contraseña, null, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Iniciar sesión" class="btn btn-primary" />
                    </div>
                </div>

            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}